export const NEXT_PUBLIC_SUPPLY_CHAIN_TRACKER_ADDRESS = process.env.NEXT_PUBLIC_SUPPLY_CHAIN_TRACKER_ADDRESS as `0x${string}`;
export const NEXT_PUBLIC_VERIFICATION_BLOCKSCOUT_URL = process.env.NEXT_PUBLIC_VERIFICATION_BLOCKSCOUT_URL;
export const NEXT_PUBLIC_ETHERSCAN_URL = process.env.NEXT_PUBLIC_ETHERSCAN_URL;
export const NEXT_PUBLIC_PINATA_API_KEY = process.env.NEXT_PUBLIC_PINATA_API_KEY;
export const NEXT_PUBLIC_PINATA_SECRET_API_KEY = process.env.NEXT_PUBLIC_PINATA_SECRET_API_KEY;